package com.primeton.eos.governor.agent.common;

public abstract interface GovernorAgentServiceExceptionCode
{
    public static final String API_CREATE_FAILED = "GATEWAY_API_11001";
    public static final String API_REMOVE_NOT_FOUND = "GATEWAY_API_11002";
    public static final String API_GET_NOT_FOUND = "GATEWAY_API_11003";
    public static final String REPO_QUERY_FAILED = "GATEWAY_REPO_QUERY_FAILED_12001";
    public static final String CONFIG_CENTER_NOT_CONNECTED = "CONFIG_CENTER_NOT_CONNECTED_13001";
    public static final String CONFIG_FILE_UPLOAD_ERROR = "CONFIG_FILE_UPLOAD_ERROR_13002";
    public static final String CONFIG_FILE_TYPE_NOT_SUPPORT = "CONFIG_FILE_TYPE_NOT_SUPPORT_13003";
    public static final String CONFIG_ITEM_ALREADY_EXIST = "CONFIG_ITEM_ALREADY_EXIST_13004";
    public static final String CONFIG_NAMESPACE_NOT_EXIST = "CONFIG_NAMESPACE_NOT_EXIST_13005";
    public static final String CONFIG_PARAM_NOT_EXIST = "CONFIG_PARAM_NOT_EXIST_13006";
    public static final String CONFIG_NAMESPACE_DUPLICATE = "CONFIG_NAMESPACE_DUPLICATE_13007";
    public static final String CONFIG_ROUTE_POLICY_ALREADY_EXIST = "CONFIG_ROUTE_POLICY_ALREADY_EXIST_13008";
    public static final String APPLICATION_CODE_DUPLICATE = "APPLICATION_CODE_DUPLICATE_14001";
    public static final String APPLICATION_NOT_EXIST = "APPLICATION_NOT_EXIST_14002";
    public static final String APPLICATION_CLUSTER_CODE_DUPLICATE = "APPLICATION_CODE_DUPLICATE_14003";
    public static final String APPLICATION_DEL_DENIED = "APPLICATION_DEL_DENIED_14004";
    public static final String APPLICATION_CLUSTER_DEL_DENIED = "APPLICATION_CLUSTER_DEL_DENIED_14005";
    public static final String APPLICATION_APOLLO_SAVE_FAILED = "APPLICATION_APOLLO_SAVE_FAILED_14006";
    public static final String APPLICATION_SEARCH_FAILED = "APPLICATION_SEARCH_FAILED_14007";
    public static final String APPLICATION_CLUSTER_NOT_EXIST = "APPLICATION_CLUSTER_NOT_EXIST_14008";
    public static final String TURBINE_URL_ERROR = "TURBINE_URL_ERROR";
    public static final String TURBINE_CREATE_APPLICATION_FAILED = "TURBINE_CREATE_APPLICATION_FAILED_14009";
    public static final String TURBINE_DELETE_APPLICATION_FAILED = "TURBINE_DELETE_APPLICATION_FAILED_14010";
    public static final String TURBINE_CREATE_CLUSTER_FAILED = "TURBINE_CREATE_CLUSTER_FAILED_14011";
    public static final String TURBINE_DELETE_CLUSTER_FAILED = "TURBINE_DELETE_CLUSTER_FAILED_14012";
    public static final String APPLICATION_CLUSTER_APOLLO_SAVE_FAILED = "APPLICATION_CLUSTER_APOLLO_SAVE_FAILED_14013";
    public static final String APPLICATION_CLUSTER_APOLLO_DELETED_FAILED = "APPLICATION_CLUSTER_APOLLO_DELETED_FAILED_14014";
    public static final String APPLICATION_SYS_CODE_DUPLICATE = "APPLICATION_CODE_DUPLICATE_15001";
    public static final String APPLICATION_SYS_DEL_DENIED = "APPLICATION_SYS_DEL_DENIED_15002";
    public static final String APPLICATION_SYS_NOT_EXIST = "APPLICATION_SYS_NOT_EXIST_15003";
    public static final String MONITOR_OPERATION_TYPE_NOT_SUPPORT = "MONITOR_OPERATION_TYPE_NOT_SUPPORT_16001";
    public static final String MONITOR_SQL_API_STATUS_ERROR = "MONITOR_SQL_API_STATUS_ERROR_16002";
    public static final String MONITOR_ES_API_STATUS_RESPONSE_ERROR = "MONITOR_ES_API_STATUS_ERROR_16003";
    public static final String MONITOR_ES_API_STATUS_TRANSFORM_ERROR = "MONITOR_ES_API_STATUS_TRANSFORM_ERROR_16004";
    public static final String APPLICATION_NODE_NOT_EXISTED = "APPLICATION_NODE_NOT_EXISTED_17001";
    public static final String APM_CONNECT_ERROR = "APM_CONNECT_ERROR_18001";
    public static final String UNKWON_ERROR = "UNKWON_ERROR_00000";
    public static final String MEDIA_TYPE_NOT_SUPPORT = "MEDIA_TYPE_NOT_SUPPORT_00001";
    public static final String APPLICATION_CONNECT_ERROR = "APPLICATION_CONNECT_ERROR_19001";
    public static final String LICENSE_PUSH_EXCEPTION = "LICENSE_PUSH_EXCEPTION_19002";
}
